name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if gh-pages branch exists and create if needed
        run: |
          if git ls-remote --exit-code --heads origin gh-pages; then
            echo "gh-pages branch exists"
          else
            echo "gh-pages does not exist. Creating..."
            git checkout --orphan gh-pages
            git reset --hard
            echo "# GitHub Pages" > README.md
            git add README.md
            git -c user.name='github-actions' -c user.email='github-actions@github.com' commit -m "Initial commit for GitHub Pages"
            git push origin gh-pages
            git checkout main
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Adjust based on your project

      - name: Install dependencies
        run: npm install # Adjust for yarn/pnpm if needed

      - name: Build project
        run: npm run build # Ensure your project outputs to 'dist'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Deploy to gh-pages
          folder: dist/personal-website # Change if your build outputs elsewhere
