name: Lint and Format Check

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Check
        run: npx prettier --check "**/*.{ts,js,json,html,scss}"
